---
- name: python install
  raw: apt install python

- name: Install aptitude packages
  apt:
    pkg:
    - aptitude
    state: latest

- name: Apt update all
  apt:
    name: "*"
    state: latest

- name: Install docker needed packages
  apt:
    pkg:
    - aptitude
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python-pip
    #update_cache: true
    state: latest

- name: Official GPG docker key
  apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Docker-ce Install
  apt:
    name: docker-ce
    state: latest

- name: Install docker
  pip:
    name: docker

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Check if Docker is up and running
  command: systemctl status docker
  register: docker_validation
  failed_when: "'Active: active (running)' not in docker_validation.stdout"
