---
- name: Grafana Key added
  apt_key:
    state: present
    url: https://packages.grafana.com/gpg.key

- name: Download grafana package
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_7.2.1_amd64.deb
    dest: /tmp

- name: Install package
  command: dpkg -i /tmp/grafana_7.2.1_amd64.deb

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: true
    state: started

- name: Check Grafana status
  command: systemctl status grafana-server
  register: grafana_validation
  failed_when: "'Active: active (running)' not in grafana_validation.stdout"
