---
# tasks file for ansible-node-app

- name: Docker Install
  import_tasks: docker_install.yml

- name: Prometheus Install
  import_tasks: prometheus_install.yml

- name: Grafana Install
  import_tasks: grafana_install.yml

- name: Config Node.js and the app
  import_tasks: node_app.yml
