---
- name: python install
  raw: printf '%s\n' 'Y' | apt install python3 > /dev/null 2>&1

- name: Install aptitude packages
  apt:
    pkg:
    - aptitude
    state: latest

- name: Apt update all
  apt:
    name: "*"
    state: latest

- name: Install docker needed packages
  apt:
    pkg:
    - aptitude
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    state: latest

- name: Official GPG docker key
  apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64"
    dest: /usr/bin/docker-compose
    mode: 0755

- name: Docker-ce Install
  apt:
    name: docker-ce
    state: latest

- name: Install Docker
  pip:
    name: docker

- name: Start and enable grafana service
  service:
    name: docker
    state: started
    enabled: true

- name: Check if Docker is up and running
  command: systemctl status docker
  register: docker_validation
  failed_when: "'Active: active (running)' not in docker_validation.stdout"
